apiVersion: v1
kind: Pod
metadata:
  name: sandbox-cpp
spec:
  containers:
    - name: sandbox-cpp-app
      image: ghcr.io/acadnet-dev/sandbox-cpp
      imagePullPolicy: "Always"
      ports:
        - containerPort: 2999
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
  imagePullSecrets:
    - name: ghcr-login-secret